version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=125571554996.dkr.ecr.ap-southeast-1.amazonaws.com/codebuildimage   
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $125571554996.dkr.ecr.ap-southeast-1.amazonaws.com/codebuildimage:latest
      - docker tag simpleapi:latest 125571554996.dkr.ecr.ap-southeast-1.amazonaws.com/codebuildimage:latest   
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $125571554996.dkr.ecr.ap-southeast-1.amazonaws.com/codebuildimage:latest

