version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - REPOSITORY-URI=125571554996.dkr.ecr.ap-southeast-1.amazonaws.com/codebuildimage
  build:
    commands:
      - echo build Docker image on `date`
      - cd src
      - docker build -t sample-express-app:latest .
      - docker tag sample-express-app:latest <125571554996.dkr.ecr.ap-southeast-1.amazonaws.com/codebuildimage
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push <125571554996.dkr.ecr.ap-southeast-1.amazonaws.com/codebuildimage


